#+TITLE: How is this site made?
#+INCLUDE: "./header.org"

* How does this site work?

A few people have asked me about how I manage this site. It changes
frequently, as I will often throw stuff up very quickly, move it
around, and take it down again.

The whole site is managed by editing local files in emacs and then a
couple of quick keystrokes push out any changes to free webhosting on
github. I'll explain each of the pieces in turn.

* It Starts with Org Mode

Org mode is a part of Emacs, and is a whole ecosystem for, well,
organizing information. [[https://orgmode.org/][Org]] files are just plain text with some
formatting conventions not unlike [[https://en.wikipedia.org/wiki/Markdown][Markdown]]. Here's an example: 

#+BEGIN_SRC code


,* How does this site work?

A few people have asked me about how I manage this site. It changes
frequently, as I will often throw stuff up very quickly, move it
around, and take it down again.

The whole site is managed by editing local files in emacs and then a
couple of quick keystrokes push out any changes to a free webhosting
github. I'll explain each of the pieces in turn.

,* It Starts with Org Mode

Org mode is a part of Emacs, and is a whole ecosystem for, well,
organizing information. [[https://orgmode.org/][Org]] files are
just plain text with some formatting conventions not unlike
[[https://en.wikipedia.org/wiki/Markdown][Markdown]]. Here's an example: 


#+END_SRC

That is the exact content that this page starts with. Because I spend
most of my day in Emacs already (see [[https://stuff.sigvaldason.com/email.html][email]]), it is super easy to just
pop into an org file, make some changes (or open a new file) and
automatically push the changes out to "production".

You can do a lot of different kinds of formats in Org-mode very easily. For example:

#+BEGIN_SRC code

,*bold*, _underline_, +strikethrough+, /italics/

| n | n^2 | n^3 |
|---+-----+-----|
| 1 |   1 |   1 |
| 2 |   4 |   8 |
| 3 |   9 |  27 |

$y=x^2$
#+END_SRC

produces:

*bold*, _underline_, +strikethrough+, /italics/

| n | n^2 | n^3 |
|---+-----+-----|
| 1 |   1 |   1 |
| 2 |   4 |   8 |
| 3 |   9 |  27 |

$y=x^2$

This is just scratching the surface or Org-mode. To quote from the [[https://orgmode.org/worg/org-faq.html][Org FAQ]]:

#+BEGIN_QUOTE
In its default setup, Org-mode offers a simple outlining and task
management environment. But it also has a huge number of features and
settings "under the hood." Advanced users have configured Org-mode for
almost every conceivable use scenario.
#+END_QUOTE


* Add in Some Packages

Emacs has a notion of packages, and there a few available for
automating the translation of org files into html. In fact Org-mode
has built-in exporting to a number of different formats, including
$\LaTeX$, PDF, ODT/Word, and html. While the default out

* Hosting at Github (& "Actions")


* Custom Domain Name


* Worth It?

If you've never used Emacs and/or org-mode, it might seem like a *lot*
of upfront work just to get over the mountain of Emacs so you can
easily manage the molehill of pushing out website updates.

I actually came to Emacs after roughly 20 years of using joe ([[https://joe-editor.sourceforge.io/][Joe's
Own Editor]]), and some of my muscle memory for text editing was so deep
that I had to customize emacs to handle many of my preferred keystrokes.

But whatever path you take to get to Emacs, it will almost certainly
be worth it. If you are an engineer, developer, or other technical
user. Emacs (plus Org-mode, dired, mu4e, git/magit, etc., etc.) is just
such a powerful tool that is worth learning to use well.


* Resources

The website [[https://systemcrafters.net/][System Crafters]] has a whole series of videos related to
Emacs, and a section devoted to website publishing with Emacs:

- [[https://systemcrafters.net/publishing-websites-with-org-mode/][Publishing Website with Org Mode]]

The above link covers ox-publish quite extensively. There's another guide to using ox-publish on the Org-mode website here:

- [[https://orgmode.org/worg/org-tutorials/org-publish-html-tutorial.html][Publishing Org-mode files to HTML]]

  
