#+TITLE: Stuff
#+INCLUDE: "./header.org"

* Overview

This is an example of a _website_ written in *Org Mode*. If this text is longer in some way, then the left justification stuff will work better.

I wonder what happens with LaTex Math: $y=x^2$

If I want to do some raw html, how about @@html:<b>@@bold text@@html:</b>@@?  

And here is an edit. And here is another edit. And here is a third edit. And now a fourth.

#+BEGIN_aside
  This is an aside. Over on the side ...
#+END_aside

And here is some slighly more complicated math:

\begin{equation}                        % arbitrary environments,
x=\sqrt{b}                              % even tables, figures, etc
\end{equation}

If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].


related to this:

[[https://www.teachmaths.org/20250105_orgmode-lesson-notes/][Emacs for Math Teachers]]  

* Links

- [[https://systemcrafters.net/][System Crafters]]
- [[https://news.ycombinator.com][Hacker News]]
  
* More crap
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.
This is really a lot of text that will help scroll off the bottom of the page.


